import type {
  AgentProfile,
  AgentSelectionProposal,
  AnalyticsOverview,
  MissionEvent,
  MissionInput,
  MissionRecord,
  MissionTask,
  RegistryAgent,
  SpendApprovalRequest,
  SpendReceipt,
  VerificationCheck,
} from "./types";

export const demoMissionInput: MissionInput = {
  title: "Trump Momentum Trade Hunt",
  template: "trump-polymarket",
  description:
    "Analyze Trump-related news and Polymarket data to recommend the best trade or call it too late or too suspicious.",
  objective:
    "Use curated agents to gather news, inspect Trump-linked markets, challenge the thesis, and return a final recommendation under 2.00 USDC.",
  successCriteria:
    "A final trade recommendation is produced with supporting evidence, receipts, and all payments explicitly approved by a human.",
  authorityWallet: "11111111111111111111111111111111",
  urgency: "high",
  executionMode: "guarded_autonomy",
  verificationMode: "human",
  maxBudget: 2,
  maxPerCall: 0.6,
  humanApprovalAbove: 0,
  challengeWindowHours: 24,
};

function isoAgo(millisecondsAgo: number): string {
  return new Date(Date.now() - millisecondsAgo).toISOString();
}

function phaseRun(
  phaseId: string,
  status: "active" | "complete" | "failed",
  detail: string,
  startedAgoMs: number,
  completedAgoMs?: number,
) {
  return {
    phaseId,
    status,
    detail,
    attempt: 1,
    startedAt: isoAgo(startedAgoMs),
    completedAt: completedAgoMs ? isoAgo(completedAgoMs) : undefined,
  };
}

const coordinatorPhases = [
  {
    id: "score_registry",
    label: "Score Registry",
    description: "Review the curated registry and score agents for the mission.",
    streams: true,
  },
  {
    id: "propose_team",
    label: "Propose Team",
    description: "Propose a starter lineup and wait for human confirmation.",
    streams: true,
  },
];

const newsPhases = [
  {
    id: "wait_for_payment",
    label: "Wait For Payment",
    description: "Pause until the human approves the paid query.",
    streams: true,
  },
  {
    id: "plan_timeline",
    label: "Plan Timeline",
    description: "Frame the exact events and time windows to inspect.",
    streams: true,
  },
  {
    id: "gather_headlines",
    label: "Gather Headlines",
    description: "Pull Trump-related headlines, quotes, and timestamps.",
    streams: true,
  },
  {
    id: "synthesize_signal",
    label: "Synthesize Signal",
    description: "Turn the raw timeline into an actionable news memo.",
    streams: true,
  },
];

const marketPhases = [
  {
    id: "wait_for_payment",
    label: "Wait For Payment",
    description: "Pause until the human approves the paid market scan.",
    streams: true,
  },
  {
    id: "map_contracts",
    label: "Map Contracts",
    description: "Find Trump-linked markets relevant to the mission objective.",
    streams: true,
  },
  {
    id: "scan_orderflow",
    label: "Scan Orderflow",
    description: "Inspect price moves, spreads, and liquidity conditions.",
    streams: true,
  },
  {
    id: "rank_markets",
    label: "Rank Markets",
    description: "Rank the most actionable markets for the downstream agents.",
    streams: true,
  },
];

const skepticPhases = [
  {
    id: "wait_for_payment",
    label: "Wait For Payment",
    description: "Pause until the human approves the replay analysis.",
    streams: true,
  },
  {
    id: "replay_timing",
    label: "Replay Timing",
    description: "Line up public signals against market movement.",
    streams: true,
  },
  {
    id: "challenge_thesis",
    label: "Challenge Thesis",
    description: "Stress test whether the apparent edge is real or stale.",
    streams: true,
  },
  {
    id: "score_suspicion",
    label: "Score Suspicion",
    description: "Estimate whether the setup is too suspicious to touch.",
    streams: true,
  },
];

const executionPhases = [
  {
    id: "draft_verdict",
    label: "Draft Verdict",
    description: "Turn the research into a concrete trade verdict.",
    streams: true,
  },
  {
    id: "package_artifact",
    label: "Package Artifact",
    description: "Produce the final recommendation artifact for the mission.",
    streams: true,
  },
];

const verifierPhases = [
  {
    id: "audit_approvals",
    label: "Audit Approvals",
    description: "Confirm that every paid action was explicitly approved.",
    streams: true,
  },
  {
    id: "check_artifacts",
    label: "Check Artifacts",
    description: "Verify the output against the mission success criteria.",
    streams: true,
  },
  {
    id: "settle_onchain",
    label: "Settle Onchain",
    description: "Record verification and release settlement on Solana.",
    streams: true,
  },
];

export const demoRegistry: RegistryAgent[] = [
  {
    id: "coordinator-1",
    slug: "mission-coordinator",
    name: "Mission Coordinator",
    role: "coordinator",
    icon: "🧭",
    description: "Plans the mission, chooses agents, and keeps the run on rails.",
    trustScore: 96,
    wallet: "3Fjx...9M8Q",
    payoutWallet: "3Fjx...9M8Q",
    verifierWallet: "8RpL...2Qx7",
    active: true,
    totalMissions: 211,
    capabilities: ["planning", "routing", "budgeting"],
    verifierCompatible: false,
    supportedServices: [],
    executionMode: "builtin",
    priceModel: "No direct spend",
    phaseSchema: coordinatorPhases,
  },
  {
    id: "trump-news-1",
    slug: "trump-news-agent",
    name: "Trump News Agent",
    role: "news",
    icon: "📰",
    description: "Collects Trump-related headlines, timestamps, and narrative shifts.",
    trustScore: 88,
    wallet: "6PaH...nX9q",
    payoutWallet: "6PaH...nX9q",
    verifierWallet: "8RpL...2Qx7",
    active: true,
    totalMissions: 142,
    capabilities: ["headline-triage", "timestamp-analysis", "signal-aggregation"],
    verifierCompatible: true,
    supportedServices: ["headline-feed.ai", "archive-indexer.ai"],
    executionMode: "builtin",
    priceModel: "Per paid query",
    phaseSchema: newsPhases,
  },
  {
    id: "polymarket-1",
    slug: "polymarket-market-agent",
    name: "Polymarket Market Agent",
    role: "market",
    icon: "📈",
    description: "Finds Trump-related markets, price swings, and market structure context.",
    trustScore: 90,
    wallet: "4MwL...7K2P",
    payoutWallet: "4MwL...7K2P",
    verifierWallet: "8RpL...2Qx7",
    active: true,
    totalMissions: 98,
    capabilities: ["market-scanning", "liquidity-checks", "price-move-analysis"],
    verifierCompatible: true,
    supportedServices: ["polymarket-scan.ai", "orderflow-ai"],
    executionMode: "builtin",
    priceModel: "Per market scan",
    phaseSchema: marketPhases,
  },
  {
    id: "skeptic-1",
    slug: "skeptic-agent",
    name: "Skeptic Agent",
    role: "skeptic",
    icon: "🕵️",
    description: "Challenges whether the move is edge, noise, or too suspicious to touch.",
    trustScore: 84,
    wallet: "8RpL...2Qx7",
    payoutWallet: "8RpL...2Qx7",
    verifierWallet: "8RpL...2Qx7",
    active: true,
    totalMissions: 76,
    capabilities: ["thesis-challenge", "timing-analysis", "asymmetry-scoring"],
    verifierCompatible: true,
    supportedServices: ["signal-replay.ai"],
    executionMode: "builtin",
    priceModel: "Per analysis run",
    phaseSchema: skepticPhases,
  },
  {
    id: "execution-1",
    slug: "execution-agent",
    name: "Execution Agent",
    role: "execution",
    icon: "⚡",
    description: "Produces the final recommendation artifact and suggested action.",
    trustScore: 91,
    wallet: "9EpQ...1NxL",
    payoutWallet: "9EpQ...1NxL",
    verifierWallet: "8RpL...2Qx7",
    active: true,
    totalMissions: 114,
    capabilities: ["artifact-generation", "trade-framing", "action-synthesis"],
    verifierCompatible: false,
    supportedServices: [],
    executionMode: "builtin",
    priceModel: "No direct spend",
    phaseSchema: executionPhases,
  },
  {
    id: "verifier-1",
    slug: "verifier-agent",
    name: "Verifier Agent",
    role: "verifier",
    icon: "✓",
    description: "Checks the mission output and ensures human-approved payments were respected.",
    trustScore: 93,
    wallet: "2aQm...7LmP",
    payoutWallet: "2aQm...7LmP",
    verifierWallet: "2aQm...7LmP",
    active: true,
    totalMissions: 330,
    capabilities: ["proof-check", "policy-audit", "artifact-verify"],
    verifierCompatible: true,
    supportedServices: [],
    executionMode: "builtin",
    priceModel: "No direct spend",
    phaseSchema: verifierPhases,
  },
];

const selectionProposal: AgentSelectionProposal = {
  id: "proposal-demo-1",
  status: "approved",
  recommendedAgentIds: ["trump-news-1", "polymarket-1", "skeptic-1", "execution-1", "verifier-1"],
  chosenAgentIds: ["trump-news-1", "polymarket-1", "skeptic-1", "execution-1", "verifier-1"],
  reason:
    "This mission needs one agent for news, one for market data, one to challenge the thesis, one to compile the recommendation, and one to verify the run.",
  createdAt: new Date(Date.now() - 185_000).toISOString(),
  respondedAt: new Date(Date.now() - 170_000).toISOString(),
};

export const demoAgents: AgentProfile[] = demoRegistry
  .filter((agent) => selectionProposal.chosenAgentIds.includes(agent.id))
  .map((agent) => {
    const runtime: Record<string, Partial<AgentProfile>> = {
      "coordinator-1": {
        selected: true,
        status: "complete",
        currentAction: "Registry proposal approved",
        currentPhaseId: "propose_team",
        currentPhaseStatus: "complete",
        phaseHistory: [
          phaseRun("score_registry", "complete", "Curated registry scored for the mission", 188_000, 184_000),
          phaseRun("propose_team", "complete", "Starter lineup proposed and approved", 183_000, 170_000),
        ],
        budgetCap: 0,
        costIncurred: 0,
      },
      "trump-news-1": {
        selected: true,
        status: "complete",
        currentAction: "News bundle finalized",
        currentPhaseId: "synthesize_signal",
        currentPhaseStatus: "complete",
        phaseHistory: [
          phaseRun("wait_for_payment", "complete", "Headline-feed payment approved", 125_000, 122_000),
          phaseRun("plan_timeline", "complete", "Mission scope reduced to the highest-signal Trump events", 121_000, 118_000),
          phaseRun("gather_headlines", "complete", "Timestamped headline batch collected", 117_000, 111_000),
          phaseRun("synthesize_signal", "complete", "News timeline memo packaged for the next agent", 110_000, 108_000),
        ],
        budgetCap: 0.45,
        costIncurred: 0.22,
      },
      "polymarket-1": {
        selected: true,
        status: "complete",
        currentAction: "Market scan and spread check complete",
        currentPhaseId: "rank_markets",
        currentPhaseStatus: "complete",
        phaseHistory: [
          phaseRun("wait_for_payment", "complete", "Market-scan payment approved", 91_000, 88_000),
          phaseRun("map_contracts", "complete", "Trump-related contracts mapped", 87_000, 83_000),
          phaseRun("scan_orderflow", "complete", "Liquidity and movement scanned", 82_000, 76_000),
          phaseRun("rank_markets", "complete", "Most relevant markets ranked for the skeptic", 75_000, 73_000),
        ],
        budgetCap: 0.55,
        costIncurred: 0.32,
      },
      "skeptic-1": {
        selected: true,
        status: "working",
        currentAction: "Testing whether the move is already priced in",
        currentPhaseId: "wait_for_payment",
        currentPhaseStatus: "active",
        phaseHistory: [
          phaseRun("wait_for_payment", "active", "Waiting for payment approval to replay timing data", 16_000),
        ],
        budgetCap: 0.3,
        costIncurred: 0,
      },
      "execution-1": {
        selected: true,
        status: "waiting",
        currentAction: "Waiting for skeptic verdict",
        currentPhaseStatus: "pending",
        phaseHistory: [],
        budgetCap: 0,
        costIncurred: 0,
      },
      "verifier-1": {
        selected: true,
        status: "waiting",
        currentAction: "Waiting for final artifact",
        currentPhaseStatus: "pending",
        phaseHistory: [],
        budgetCap: 0,
        costIncurred: 0,
      },
    };

    return {
      ...agent,
      ...runtime[agent.id],
    };
  });

export const demoTasks: MissionTask[] = [
  {
    id: "task-plan",
    title: "Select agents from registry",
    objective: "Choose the curated agents best suited for the mission and wait for human approval.",
    assignedAgent: "coordinator",
    assignedAgentId: "coordinator-1",
    dependencies: [],
    budgetAllocation: 0,
    approvedServices: [],
    verificationExpectation: "Human-approved agent selection proposal",
    status: "complete",
  },
  {
    id: "task-news",
    title: "Build the Trump news timeline",
    objective: "Collect the most relevant Trump-related events, timestamps, and public narrative shifts.",
    assignedAgent: "news",
    assignedAgentId: "trump-news-1",
    dependencies: ["task-plan"],
    budgetAllocation: 0.45,
    approvedServices: ["headline-feed.ai", "archive-indexer.ai"],
    verificationExpectation: "Timestamped news summary with links",
    outputArtifactRef: "artifact://mission/news-dossier",
    status: "complete",
  },
  {
    id: "task-market",
    title: "Scan Trump-linked Polymarket markets",
    objective: "Fetch relevant markets, prices, spread, and recent movement before proposing a trade.",
    assignedAgent: "market",
    assignedAgentId: "polymarket-1",
    dependencies: ["task-plan"],
    budgetAllocation: 0.55,
    approvedServices: ["polymarket-scan.ai", "orderflow-ai"],
    verificationExpectation: "Ranked markets with timing notes",
    outputArtifactRef: "artifact://mission/market-scan",
    status: "complete",
  },
  {
    id: "task-skeptic",
    title: "Challenge the edge",
    objective: "Decide whether the thesis is real, stale, or too suspicious to touch.",
    assignedAgent: "skeptic",
    assignedAgentId: "skeptic-1",
    dependencies: ["task-news", "task-market"],
    budgetAllocation: 0.3,
    approvedServices: ["signal-replay.ai"],
    verificationExpectation: "Explicit asymmetry score and caution flags",
    outputArtifactRef: "artifact://mission/skeptic-memo",
    status: "active",
  },
  {
    id: "task-execution",
    title: "Prepare final recommendation",
    objective: "Produce the final answer: good trade, no trade, too late, or too suspicious.",
    assignedAgent: "execution",
    assignedAgentId: "execution-1",
    dependencies: ["task-skeptic"],
    budgetAllocation: 0,
    approvedServices: [],
    verificationExpectation: "Final recommendation artifact",
    status: "waiting",
  },
  {
    id: "task-verify",
    title: "Verify output and approvals",
    objective: "Ensure every payment was human-approved and the final answer matches the evidence.",
    assignedAgent: "verifier",
    assignedAgentId: "verifier-1",
    dependencies: ["task-execution"],
    budgetAllocation: 0,
    approvedServices: [],
    verificationExpectation: "Verifier verdict and proof hash",
    status: "waiting",
  },
];

export const demoReceipts: SpendReceipt[] = [
  {
    receiptId: "receipt-1",
    missionId: "mission-demo-1",
    agentId: "trump-news-1",
    serviceWallet: "headline-feed.ai",
    amount: 0.22,
    purpose: "news_timeline_bundle",
    toolName: "headline-feed.ai",
    timestamp: new Date(Date.now() - 118_000).toISOString(),
    txSignature: "2aQw...Qr8m",
  },
  {
    receiptId: "receipt-2",
    missionId: "mission-demo-1",
    agentId: "polymarket-1",
    serviceWallet: "polymarket-scan.ai",
    amount: 0.32,
    purpose: "market_scan_bundle",
    toolName: "polymarket-scan.ai",
    timestamp: new Date(Date.now() - 84_000).toISOString(),
    txSignature: "7kLm...2Qa1",
  },
];

export const demoSpendApprovals: SpendApprovalRequest[] = [
  {
    id: "approval-1",
    missionId: "mission-demo-1",
    agentId: "trump-news-1",
    status: "approved",
    amount: 0.22,
    service: "headline-feed.ai",
    purpose: "news_timeline_bundle",
    justification: "Pull a timestamped batch of recent Trump headlines and structured story metadata.",
    requestedAt: new Date(Date.now() - 125_000).toISOString(),
    respondedAt: new Date(Date.now() - 122_000).toISOString(),
    txSignature: "2aQw...Qr8m",
  },
  {
    id: "approval-2",
    missionId: "mission-demo-1",
    agentId: "polymarket-1",
    status: "approved",
    amount: 0.32,
    service: "polymarket-scan.ai",
    purpose: "market_scan_bundle",
    justification: "Scan current Trump-tagged markets for price changes, spread, and liquidity context.",
    requestedAt: new Date(Date.now() - 91_000).toISOString(),
    respondedAt: new Date(Date.now() - 88_000).toISOString(),
    txSignature: "7kLm...2Qa1",
  },
  {
    id: "approval-3",
    missionId: "mission-demo-1",
    agentId: "skeptic-1",
    status: "pending",
    amount: 0.08,
    service: "signal-replay.ai",
    purpose: "skeptic_signal_replay",
    justification: "Replay the timing between public Trump news and market movement to estimate whether the edge is stale or too suspicious.",
    requestedAt: new Date(Date.now() - 16_000).toISOString(),
  },
];

export const demoVerificationChecks: VerificationCheck[] = [
  { id: "selection", label: "Human approved the selected agents", status: "passed" },
  { id: "news", label: "News timeline assembled", status: "passed" },
  { id: "market", label: "Market scan completed", status: "passed" },
  { id: "skeptic", label: "Skeptic verdict still pending", status: "running" },
  { id: "payments", label: "Every payment requires explicit approval", status: "running" },
];

export const demoEvents: MissionEvent[] = [
  {
    id: "event-1",
    missionId: "mission-demo-1",
    type: "MISSION_CREATED",
    label: "Mission created — budget authorized and vault initialized",
    txSignature: "5pQw...Rz1m",
    createdAt: new Date(Date.now() - 190_000).toISOString(),
  },
  {
    id: "event-2",
    missionId: "mission-demo-1",
    type: "SELECTION_PROPOSED",
    label: "Coordinator proposed 5 registry agents for the mission",
    proposalId: selectionProposal.id,
    agentIds: selectionProposal.recommendedAgentIds,
    createdAt: new Date(Date.now() - 182_000).toISOString(),
  },
  {
    id: "event-3",
    missionId: "mission-demo-1",
    type: "SELECTION_APPROVED",
    label: "Human approved the selected agents",
    proposalId: selectionProposal.id,
    agentIds: selectionProposal.chosenAgentIds,
    createdAt: new Date(Date.now() - 170_000).toISOString(),
  },
  {
    id: "event-4",
    missionId: "mission-demo-1",
    type: "SPEND_APPROVAL_REQUIRED",
    label: "Trump News Agent requested 0.22 USDC for headline-feed.ai",
    agentId: "trump-news-1",
    amount: 0.22,
    service: "headline-feed.ai",
    approvalId: "approval-1",
    createdAt: new Date(Date.now() - 125_000).toISOString(),
  },
  {
    id: "event-5",
    missionId: "mission-demo-1",
    type: "SPEND_APPROVED",
    label: "Human approved 0.22 USDC → headline-feed.ai",
    agentId: "trump-news-1",
    amount: 0.22,
    service: "headline-feed.ai",
    txSignature: "2aQw...Qr8m",
    approvalId: "approval-1",
    createdAt: new Date(Date.now() - 122_000).toISOString(),
  },
  {
    id: "event-6",
    missionId: "mission-demo-1",
    type: "TASK_COMPLETE",
    label: "Trump News Agent delivered the news timeline",
    taskId: "task-news",
    agentId: "trump-news-1",
    outputRef: "artifact://mission/news-dossier",
    createdAt: new Date(Date.now() - 108_000).toISOString(),
  },
  {
    id: "event-6b",
    missionId: "mission-demo-1",
    type: "AGENT_PHASE_COMPLETED",
    label: "Trump News Agent finished synthesizing the news signal",
    agentId: "trump-news-1",
    phaseId: "synthesize_signal",
    detail: "News timeline memo packaged for the next agent",
    attempt: 1,
    createdAt: new Date(Date.now() - 108_000).toISOString(),
  },
  {
    id: "event-7",
    missionId: "mission-demo-1",
    type: "SPEND_APPROVAL_REQUIRED",
    label: "Polymarket Agent requested 0.32 USDC for polymarket-scan.ai",
    agentId: "polymarket-1",
    amount: 0.32,
    service: "polymarket-scan.ai",
    approvalId: "approval-2",
    createdAt: new Date(Date.now() - 91_000).toISOString(),
  },
  {
    id: "event-8",
    missionId: "mission-demo-1",
    type: "SPEND_APPROVED",
    label: "Human approved 0.32 USDC → polymarket-scan.ai",
    agentId: "polymarket-1",
    amount: 0.32,
    service: "polymarket-scan.ai",
    txSignature: "7kLm...2Qa1",
    approvalId: "approval-2",
    createdAt: new Date(Date.now() - 88_000).toISOString(),
  },
  {
    id: "event-9",
    missionId: "mission-demo-1",
    type: "TASK_COMPLETE",
    label: "Polymarket Agent ranked the current Trump markets",
    taskId: "task-market",
    agentId: "polymarket-1",
    outputRef: "artifact://mission/market-scan",
    createdAt: new Date(Date.now() - 73_000).toISOString(),
  },
  {
    id: "event-9b",
    missionId: "mission-demo-1",
    type: "AGENT_PHASE_COMPLETED",
    label: "Polymarket Agent ranked the strongest live contracts",
    agentId: "polymarket-1",
    phaseId: "rank_markets",
    detail: "Markets ranked for downstream challenge and execution",
    attempt: 1,
    createdAt: new Date(Date.now() - 73_000).toISOString(),
  },
  {
    id: "event-10",
    missionId: "mission-demo-1",
    type: "SPEND_APPROVAL_REQUIRED",
    label: "Skeptic Agent is waiting for payment approval to replay the timing signal",
    agentId: "skeptic-1",
    amount: 0.08,
    service: "signal-replay.ai",
    approvalId: "approval-3",
    createdAt: new Date(Date.now() - 16_000).toISOString(),
  },
  {
    id: "event-11",
    missionId: "mission-demo-1",
    type: "AGENT_PHASE_STARTED",
    label: "Skeptic Agent is paused in its timing replay phase",
    agentId: "skeptic-1",
    phaseId: "wait_for_payment",
    detail: "Waiting for payment approval to replay timing data",
    attempt: 1,
    createdAt: new Date(Date.now() - 16_000).toISOString(),
  },
];

export const demoMissionRecord: MissionRecord = {
  id: "mission-demo-1",
  input: demoMissionInput,
  status: "awaiting_spend_approval",
  elapsedLabel: "3m 08s",
  budget: {
    totalBudget: 2,
    maxPerCall: 0.6,
    humanApprovalAbove: 0,
    reserved: 0.08,
    spent: 0.54,
    remaining: 1.38,
  },
  registry: demoRegistry,
  agents: demoAgents,
  selectedAgentIds: selectionProposal.chosenAgentIds,
  selectionProposal,
  pendingSpendApprovals: demoSpendApprovals.filter((approval) => approval.status === "pending"),
  tasks: demoTasks,
  events: demoEvents,
  verificationChecks: demoVerificationChecks,
  receipts: demoReceipts,
  finalResult: {
    verdict: "too_sus",
    headline: "The move looks early, thin, and hard to trust without clearer public catalysts.",
    summary:
      "The news and market agents found a sharp move in a thin Trump-linked market, but the skeptic agent still needs its replay pass before the final verdict is locked.",
    confidence: 0.71,
    keyPoints: [
      "The current best setup still depends on a timing replay.",
      "Two payments have been approved and executed.",
      "One further payment is waiting on explicit human approval.",
    ],
  },
  proof: {
    missionId: "mission-demo-1",
    outputSummary:
      "Awaiting skeptic replay approval before locking the final trade recommendation.",
    artifactLinks: [
      "artifact://mission/news-dossier",
      "artifact://mission/market-scan",
    ],
    resultHash: "proof_0x47cc1a94",
    apiReceiptHashes: ["receipt-1", "receipt-2"],
    txHashes: ["5pQw...Rz1m", "2aQw...Qr8m", "7kLm...2Qa1"],
    completionConfidence: 0.71,
  },
  settlement: {
    state: "awaiting_spend_approval",
    settledAmount: 0,
    refundedAmount: 0,
    protocolFee: 0,
  },
  reputationDeltas: [],
  chain: {
    programId: "MissionMesh11111111111111111111111111111111",
    missionPda: "mission_demo_1_pda",
    verificationPda: "verification_demo_1_pda",
    vaultAta: "vault_demo_1_ata",
    rpcProvider: "rpcfast-ready",
    rpcHttpUrl: "Configured at runtime",
    rpcWsUrl: "Configured at runtime",
    rpcStreamingEnabled: true,
  },
};

export const demoAnalytics: AnalyticsOverview = {
  completionRate: "93.1%",
  averageDuration: "5m 12s",
  averageBudgetUsed: "1.18",
  verificationPassRate: "99.0%",
  totalValueSettled: "$2,840",
};
